name: run-test

# Current values are for testing. Update later.
on:
  push:
    branches:
    - feature/vue-electron-env-setup

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v1

    - name: Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: npm install
      run: |
        npm ci
      env:
        CI: true

    - name: test
      run: |
        npm run unit
      env:
        CI: true