name: Testing

# Current values are for testing. Update later.
on:
  pull_request:
    branches:
      - develop

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v1

    - name: Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: npm install
      run: npm ci
      env:
        CI: true

    - name: Run headless test
      uses: GabrielBB/xvfb-action@v1.2
      with:
        run: npm run test:full